### ISSUE TITLE
我skillapi释放一下技能粒子特效就会出现

### ISSUE THREAD

**Issue by Niinnee** [Saukiya/SX-Attribute#1]

**Comment by Niinnee** [comment]
[00:29:02] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to SX-Attribute v3.2.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at com.rit.sucy.player.Protection.canAttack(Protection.java:84) ~[?:?]
	at com.rit.sucy.player.Protection.canAttack(Protection.java:54) ~[?:?]
	at com.sucy.skill.api.DefaultCombatProtection.canAttack(DefaultCombatProtection.java:32) ~[?:?]
	at com.sucy.skill.api.DefaultCombatProtection.canAttack(DefaultCombatProtection.java:21) ~[?:?]
	at com.sucy.skill.data.Settings.canAttack(Settings.java:379) ~[?:?]
	at com.sucy.skill.data.Settings.isAlly(Settings.java:400) ~[?:?]
	at com.sucy.skill.dynamic.target.TargetComponent.isValidTarget(TargetComponent.java:153) ~[?:?]
	at com.sucy.skill.dynamic.target.TargetComponent.lambda$determineTargets$1(TargetComponent.java:135) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_102]
	at com.sucy.skill.dynamic.target.TargetComponent.determineTargets(TargetComponent.java:131) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.OffsetTarget.getTargets(OffsetTarget.java:59) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:54) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:212) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:55) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:212) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:55) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:212) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:55) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:212) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:55) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:212) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.trigger.TriggerComponent.execute(TriggerComponent.java:40) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.trigger.TriggerComponent.trigger(TriggerComponent.java:23) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.DynamicSkill.trigger(DynamicSkill.java:332) [SkillAPI.jar:?]
	at com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:255) [SkillAPI.jar:?]
	at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:1794) [SkillAPI.jar:?]
	at com.sucy.skill.api.player.PlayerSkillBar.apply(PlayerSkillBar.java:229) [SkillAPI.jar:?]
	at com.sucy.skill.listener.BarListener.onCast(BarListener.java:367) [SkillAPI.jar:?]
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1163) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at github.saukiya.sxattribute.api.SXAPI.getMaxHealth(SXAPI.java:256) ~[?:?]
	at github.saukiya.sxattribute.listener.OnHealthChangeListener.OnEntityDamageEvent(OnHealthChangeListener.java:132) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	... 50 more

**Comment by Niinnee** [comment]
MM相关也会爆错？这个是skillapi的技能问题吗？

**Comment by Niinnee** [comment]
我用屏蔽插件给屏蔽了这些报错，我觉得应该是skillapi的问题，不好意思打扰您了
