### ISSUE TITLE
你好，加载的时候报错

### ISSUE THREAD

**Issue by EllenChang2132** [Saukiya/SX-Attribute#15]
09:51:37 ERROR]: Error occurred while enabling SX-Attribute v3.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: github/saukiya/sxitem/data/expression/ExpressionHandler
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at SX-Attribute-3.7.0-all.jar/github.saukiya.sxattribute.data.RandomStringManager.<init>(RandomStringManager.java:23) ~[SX-Attribute-3.7.0-all.jar:?]
        at SX-Attribute-3.7.0-all.jar/github.saukiya.sxattribute.SXAttribute.onEnable(SXAttribute.java:244) ~[SX-Attribute-3.7.0-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: github.saukiya.sxitem.data.expression.ExpressionHandler
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 22 more
[09:51:37 INFO]: [SX-Attribute] Disabling SX-Attribute v3.7.0
[09:51:37 ERROR]: Error occurred while disabling SX-Attribute v3.7.0
java.lang.NullPointerException: Cannot invoke "github.saukiya.sxattribute.data.attribute.SXAttributeManager.onAttributeDisable()" because "github.saukiya.sxattribute.SXAttribute.attributeManager" is null
        at SX-Attribute-3.7.0-all.jar/github.saukiya.sxattribute.SXAttribute.onDisable(SXAttribute.java:296) ~[SX-Attribute-3.7.0-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-0927bfb]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

上面是报的错 
服务端：leaf
版本：1.21.1
插件不细说
sxitem版本是：4.2.2
mm版本是5.7.2
以上出现问题 
已经进行复刻
但是找不出来是什么问题......

**Comment by Saukiya** [comment]
SX-Item 需要升到4.4.0
(没给项目开通知 issue之前没看到
