### ISSUE TITLE
后台不停报错

### ISSUE THREAD

**Issue by Dty903** [Saukiya/SX-Attribute#8]
服务端版本1.12.2
不停刷以下信息：
[SX-Attribute] Task #80 for SX-Attribute v3.6.4-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/spigotmc/SpigotConfig
        at github.saukiya.sxattribute.data.attribute.sub.attack.Damage.correct(Damage.java:168) ~[?:?]
        at github.saukiya.sxattribute.data.attribute.SXAttributeData.correct(SXAttributeData.java:103) ~[?:?]
        at github.saukiya.sxattribute.data.attribute.SXAttributeManager.getEntityData(SXAttributeManager.java:172) ~[?:?]
        at github.saukiya.sxattribute.api.SXAPI.getEntityData(SXAPI.java:64) ~[?:?]
        at github.saukiya.sxattribute.data.attribute.sub.defence.HealthRegen$1.run(HealthRegen.java:32) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:360) [CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [CraftBukkit-1.12.2.jar:git-Bukkit-f4830a1]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassNotFoundException: org.spigotmc.SpigotConfig
        ... 12 more

**Comment by Saukiya** [comment]
兼容性问题吧，没有SpigotConfig这个类

**Comment by Saukiya** [comment]
（3.6.4那条分支是肥洋洋的,他没维护了呢 [MCBBS](https://www.mcbbs.net/thread-1083840-1-1.html) [Gitee](https://gitee.com/keplero/SX-Attribute)
我这边维护SX-Attribute的话也不是很方便（4.x还能鸽

属性插件目前可以考虑AP，我这边主要维护的还是SX-Item
